channels:
- pytorch
- conda-forge
- defaults
dependencies:
- attrs=19.3.0
- autopep8=1.4.4
- backcall=0.1.0
- bleach=3.1.0
- ca-certificates=2020.7.22
- certifi=2020.6.20
- cffi=1.13.0
- colorama=0.4.1
- cudatoolkit=10.1.168
- cycler=0.10.0
- decorator=4.4.0
- defusedxml=0.6.0
- entrypoints=0.3
- freetype=2.10.0
- icu=64.2
- importlib_metadata
- intel-openmp=2019.4
- ipykernel=5.1.3
- ipython=7.8.0
- ipython_genutils=0.2.0
- ipywidgets=7.5.1
- jedi=0.15.1
- jinja2=2.10.3
- jpeg=9c
- jsonschema=3.1.1
- kiwisolver=1.2.0
- libblas=3.8.0
- libcblas=3.8.0
- libclang=9.0.0
- liblapack=3.8.0
- libpng=1.6.37
- libsodium=1.0.17
- libtiff=4.0.10
- lz4-c=1.8.3
- markupsafe=1.1.1
- matplotlib
- matplotlib-base
- mistune=0.8.4
- mkl=2019.4
- more-itertools=7.2.0
- nbconvert=5.6.0
- nbformat=4.4.0
- ninja=1.9.0
- notebook=6.0.1
- numpy=1.17.1
- olefile=0.46
- openssl=1.1.1g
- pandoc=2.7.3
- pandocfilters=1.4.2
- parso=0.5.1
- pickleshare=0.7.5
- pillow=6.2.1
- pip=19.3.1
- prometheus_client=0.7.1
- prompt_toolkit=2.0.10
- pycodestyle=2.5.0
- pycparser=2.19
- pygments=2.4.2
- pyparsing=2.4.7
- pyqt=5.12.3
- pyrsistent=0.15.4
- python=3.7.*
- python-dateutil=2.8.0
- pytorch
- pyzmq=18.1.0
- qt=5.12.5
- qtconsole=4.5.5
- send2trash=1.5.0
- setuptools=41.4.0
- six=1.12.0000
- sqlite=3.30.1
- terminado=0.8.2
- testpath=0.4.2
- tk=8.6.9
- torchvision
- tornado=6.0.3
- traitlets=4.3.3
- wcwidth=0.1.7
- webencodings=0.5.1
- wheel=0.33.6
- widgetsnbextension=3.5.1
- xz=5.2.4
- yaml=0.2.5
- zeromq=4.3.2
- zipp=0.6.0
- zlib=1.2.11
- zstd=1.4.3
- pip:
  - absl-py==0.10.0
  - cachetools==4.1.1
  - chardet==3.0.4
  - google-auth==1.21.1
  - google-auth-oauthlib==0.4.1
  - grpcio==1.32.0
  - idna==2.10
  - joblib==0.16.0
  - markdown==3.2.2
  - networkx==2.5
  - numexpr==2.7.1
  - oauthlib==3.1.0
  - pandas==1.0.5
  - protobuf==3.13.0
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pyqt5-sip==4.19.18
  - pyqtwebengine==5.12.1
  - pytz==2020.1
  - pyyaml==5.3.1
  - requests==2.24.0
  - requests-oauthlib==1.3.0
  - rsa==4.6
  - scikit-learn==0.23.1
  - scipy==1.5.1
  - sklearn==0.0
  - tables==3.6.1
  - tensorboard==2.3.0
  - tensorboard-plugin-wit==1.7.0
  - threadpoolctl==2.1.0
  - torchsummary==1.5.1
  - urllib3==1.25.10
  - werkzeug==1.0.1
name: NeuralNILM
